# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finalUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 190)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.showPathTxt = QtWidgets.QTextBrowser(self.centralwidget)
        self.showPathTxt.setGeometry(QtCore.QRect(20, 20, 261, 71))
        self.showPathTxt.setObjectName("showPathTxt")
        self.choosFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.choosFileButton.setGeometry(QtCore.QRect(290, 20, 151, 71))
        self.choosFileButton.setObjectName("choosFileButton")
        self.exportExcel = QtWidgets.QPushButton(self.centralwidget)
        self.exportExcel.setGeometry(QtCore.QRect(20, 110, 421, 31))
        self.exportExcel.setObjectName("exportExcel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.showPathTxt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Choose Pdf files to transform to excel.</p></body></html>"))
        self.choosFileButton.setText(_translate("MainWindow", "Choose files"))
        self.exportExcel.setText(_translate("MainWindow", "Export excel to path"))
