# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PdfTxt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("PDF to txt")
        MainWindow.resize(640, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chooseFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseFileButton.setGeometry(QtCore.QRect(470, 20, 121, 31))
        self.chooseFileButton.setObjectName("chooseFileButton")
        self.filePathTxt = QtWidgets.QTextBrowser(self.centralwidget)
        self.filePathTxt.setGeometry(QtCore.QRect(50, 20, 371, 31))
        self.filePathTxt.setObjectName("filePathTxt")
        self.transToTxtButton = QtWidgets.QPushButton(self.centralwidget)
        self.transToTxtButton.setGeometry(QtCore.QRect(50, 60, 541, 23))
        self.transToTxtButton.setObjectName("transToTxtButton")
        self.showTxt = QtWidgets.QTextBrowser(self.centralwidget)
        self.showTxt.setGeometry(QtCore.QRect(50, 90, 541, 201))
        self.showTxt.setObjectName("showTxt")
        self.choosePathButton = QtWidgets.QPushButton(self.centralwidget)
        self.choosePathButton.setGeometry(QtCore.QRect(390, 310, 111, 31))
        self.choosePathButton.setObjectName("choosePathButton")
        self.saveFilePathTxt = QtWidgets.QTextBrowser(self.centralwidget)
        self.saveFilePathTxt.setGeometry(QtCore.QRect(50, 310, 321, 31))
        self.saveFilePathTxt.setReadOnly(False)
        self.saveFilePathTxt.setObjectName("saveFilePathTxt")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(510, 310, 81, 31))
        self.saveButton.setObjectName("saveButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PDF to txt"))
        self.chooseFileButton.setText(_translate("MainWindow", "Choose File"))
        self.filePathTxt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PDF file only.</p></body></html>"))
        self.transToTxtButton.setText(_translate("MainWindow", "Trans to TXT "))
        self.showTxt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The result after transform will show here.</p></body></html>"))
        self.choosePathButton.setText(_translate("MainWindow", "Choose Path"))
        self.saveFilePathTxt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Choose Folder.</p></body></html>"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
