# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(877, 278)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.showExcel = QtWidgets.QTableWidget(self.centralwidget)
        self.showExcel.setGeometry(QtCore.QRect(40, 20, 821, 131))
        self.showExcel.setObjectName("showExcel")
        self.showExcel.setColumnCount(0)
        self.showExcel.setRowCount(0)
        self.showNerButton = QtWidgets.QPushButton(self.centralwidget)
        self.showNerButton.setGeometry(QtCore.QRect(640, 140, 221, 41))
        self.showNerButton.setObjectName("showNerButton")
        self.saveNerButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveNerButton.setGeometry(QtCore.QRect(640, 210, 221, 41))
        self.saveNerButton.setObjectName("saveNerButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 170, 441, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.choosePathButton = QtWidgets.QPushButton(self.centralwidget)
        self.choosePathButton.setGeometry(QtCore.QRect(500, 170, 111, 31))
        self.choosePathButton.setObjectName("choosePathButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.showNerButton.setText(_translate("MainWindow", "Show NER in browser"))
        self.saveNerButton.setText(_translate("MainWindow", "Save NER as HTML file"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">choose path to save ner.</p></body></html>"))
        self.choosePathButton.setText(_translate("MainWindow", "Choose Path"))
